cafnet:
  name: cafnet
  hparams:
    in_channels: 3
    embed_dims: [64, 64, 128, 256]
    num_heads: [1, 2, 4, 8]
    mlp_ratios: [4, 4, 4, 4]
    reduction_ratios: [8, 4, 2, 1]
    depths: [2, 2, 2, 2]
    crackam: true
    crackspam: true
    attn_gate: true

cafnet_mbnv3l:
  name: cafnet_mbnv3l
  hparams:
    in_channels: 3
    embed_dims: [16, 24, 40, 112]
    num_heads: [1, 2, 4, 8]
    mlp_ratios: [4, 4, 4, 4]
    reduction_ratios: [8, 4, 2, 1]
    depths: [2, 2, 2, 2]
    crackam: true
    crackspam: true
    attn_gate: true

dtrcnet:
  name: dtrcnet
  hparams:
    n_channels: 3
    n_classes: 1

unet:
  name: unet
  hparams:
    encoder_name: "resnet18"
    encoder_weights: "imagenet"
    in_channels: 3
    classes: 1

hrsegnet:
  name: hrsegnet
  hparams:
    in_channels: 3
    base: 32
    num_classes: 1

segformer:
  name: "segformer"
  hparams:
    encoder_name: "mit_b1"      
    encoder_weights: "imagenet"
    in_channels: 3
    classes: 1

segnet:
  name: "segnet"
  hparams:
    encoder_name: "resnet18"   
    encoder_weights: "imagenet"
    in_channels: 3
    classes: 1

deeplabv3plus:
  name: "deeplabv3plus"
  hparams:
    encoder_name: "resnet50"   # DeepLabV3+ thường chạy rất tốt với ResNet hoặc ResNeXt
    encoder_weights: "imagenet"
    in_channels: 3
    classes: 1

dcsnet:
  name: "dcsnet"
  hparams:
    nclass: 1
    mode: 'train'

hacnetv2:
  name: "hacnetv2"
  hparams:
    channels: 32